print('===Desafio 3===')
n1=int(input('Digite um valor:'))
n2=int(input('Digite um valor:'))
s= n1+n2
print('A soma entre {} e {} vai dar {}'.format(n1,n2,s))
print()
print('Parte 2')
n1=int(input('Digite um valor:'))
n2=int(input('Digite um valor:'))
sub=(n1-n2)
print('A subtração vale',sub)
print()
print('===Desafio 4===')
n1=str(input('Digite qualquer coisa:'))
print(f' O tipo primitivo desse valor é:{type(n1)}')
print(f'É um número?:{n1.isnumeric()}')
print('É alfabético?',n1.isalpha())
print('Ele é alfanumérico?',n1.isalnum())
print('A palavra está capitalizada?',n1.istitle())
print('Só tem espaço?',n1.isspace())
print('É um digito?',n1.isdigit())
print('Está em maiúsculas?',n1.isupper())
print('Está em minúsculas?',n1.islower())